### ISSUE TITLE
a potential deadlock related to projects that are connected to EGit

### ISSUE THREAD

**Issue by reprogrammer** [reprogrammer/cascade#29]
Eclipse freezes when I run Cascade on the [jolden-mst](https://github.com/reprogrammer/tqi-study) project.

<pre>
org.eclipse.team.core.TeamException: The resource tree is locked for modifications.
    at org.eclipse.team.internal.core.TeamPlugin.wrapException(TeamPlugin.java:128)
    at org.eclipse.team.core.RepositoryProvider.unmap(RepositoryProvider.java:289)
    at org.eclipse.egit.core.project.GitProjectData.logAndUnmapGoneMappedResource(GitProjectData.java:534)
    at org.eclipse.egit.core.project.GitProjectData.map(GitProjectData.java:497)
    at org.eclipse.egit.core.project.GitProjectData.remapAll(GitProjectData.java:471)
    at org.eclipse.egit.core.project.GitProjectData.load(GitProjectData.java:464)
    at org.eclipse.egit.core.project.GitProjectData.get(GitProjectData.java:204)
    at org.eclipse.egit.core.GitProvider.getData(GitProvider.java:86)
    at org.eclipse.egit.core.project.RepositoryMapping.getMapping(RepositoryMapping.java:268)
    at org.eclipse.egit.core.Activator$AutoShareProjects.visitConnect(Activator.java:311)
    at org.eclipse.egit.core.Activator$AutoShareProjects.access$0(Activator.java:298)
    at org.eclipse.egit.core.Activator$AutoShareProjects$1.visit(Activator.java:280)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:69)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:49)
    at org.eclipse.egit.core.Activator$AutoShareProjects.resourceChanged(Activator.java:277)
    at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
    at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
    at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:396)
    at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1531)
    at org.eclipse.core.internal.resources.Project.internalCopy(Project.java:755)
    at org.eclipse.core.internal.resources.Project.copy(Project.java:234)
    at org.eclipse.core.internal.resources.Resource.copy(Resource.java:544)
    at checker.framework.quickfixes.WorkspaceUtils.copyResource(WorkspaceUtils.java:95)
    at checker.framework.change.propagator.ShadowProject.updateToPrimaryProjectWithChanges(ShadowProject.java:148)
    at checker.framework.errorcentric.view.views.MarkerResolutionTreeNode$1.run(MarkerResolutionTreeNode.java:69)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
Caused by: org.eclipse.core.internal.resources.ResourceException: The resource tree is locked for modifications.
    at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:116)
    at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2283)
    at org.eclipse.core.internal.resources.Project.touch(Project.java:1403)
    at org.eclipse.team.core.RepositoryProvider.unmap(RepositoryProvider.java:277)
    ... 27 more
!SUBENTRY 1 org.eclipse.team.core 4 380 2014-04-21 11:17:55.512
!MESSAGE The resource tree is locked for modifications.
!STACK 1
</pre>

**Comment by reprogrammer** [comment]
I used `ResourcesPlugin.getWorkspace().run(job, ResourcesPlugin.getWorkspace().getRoot(),       IWorkspace.AVOID_UPDATE, null)` in methods `checker.framework.errorcentric.view.views.MarkerResolutionTreeNode.computeChangeEffectAsync()` and `checker.framework.change.propagator.ShadowProjectFactory.get()` that modify the workspace. `IWorkspace.run` avoids notifications while the compound operation is in progress. However, EGit throws an exception as soon as the compound operation is finished and the notifications are broadcast. This may be a bug in EGit because when I disconnect the project from EGit, I don't get the exception.

**Comment by reprogrammer** [comment]
I'm going to close this issue for now because disconnecting the project from EGit is a reasonable workaround.
