### ISSUE TITLE
Cascade throws NullPointerException on BH when the def and use of a field are in different files

### ISSUE THREAD

**Issue by reprogrammer** [reprogrammer/cascade#54]
Cascade throws the following exception when I run it on jolden-bh.

<pre>
!ENTRY org.eclipse.core.jobs 4 2 2014-04-26 13:18:50.688
!MESSAGE An internal error occurred during: "Computing the effect of: Change field root to @Nullable Node".
!STACK 0
java.lang.NullPointerException
    at checker.framework.quickfixes.variabledeclarationfixer.VariableDeclarationFixer.getProposal(VariableDeclarationFixer.java:74)
    at checker.framework.quickfixes.descriptors.FixerProposalFactory.createProposal(FixerProposalFactory.java:24)
    at checker.framework.quickfixes.descriptors.FixerProposalFactory.createResolution(FixerProposalFactory.java:31)
    at checker.framework.change.propagator.ResolutionHelper.createActionableResolutions(ResolutionHelper.java:80)
    at checker.framework.change.propagator.ResolutionHelper.getResolutions(ResolutionHelper.java:37)
    at checker.framework.change.propagator.ShadowProject.getResolutions(ShadowProject.java:81)
    at checker.framework.errorcentric.view.views.ChangeComputationJob.run(ChangeComputationJob.java:63)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
</pre>

**Comment by reprogrammer** [comment]
I believe the problem is that the compilation unit object is set incorrectly. The fixer uses the compilation unit of the marker not the variable declaration. Since the marker is in a different compilation unit than that of the variable declaration, the program fails to locate the AST node corresponding to the variable declaration. Method `VariableDeclarationFixerDescriptorFactory.doGet()` should change to set the compilation unit to the one that declares the variable.

Currently, the code uses the binding key of the variable declaration and the compilation unit that declares the variable to locate the variable declaration. One idea to fix this bug is to use the binding key of the declaration of the variable and the binding key of the enclosing class of the variable declaration to locate the variable declaration.
