### ISSUE TITLE
NullPointerException when trying to annotate the field of an innerclass declared inside a method

### ISSUE THREAD

**Issue by reprogrammer** [reprogrammer/cascade#58]
When I ran the tool on jolden-bh, it threw the following exception:

<pre>
!MESSAGE An internal error occurred during: "Computing the effect of: Change return type of nextElement to @Nullable Object".
!STACK 0
java.lang.NullPointerException
    at checker.framework.quickfixes.variabledeclarationfixer.VariableDeclarationFixer.getProposal(VariableDeclarationFixer.java:74)
    at checker.framework.quickfixes.FixerDescriptorApplier.apply(FixerDescriptorApplier.java:28)
    at checker.framework.change.propagator.ShadowProject.updateToPrimaryProjectWithChanges(ShadowProject.java:89)
    at checker.framework.errorcentric.view.views.ChangeComputationJob.run(ChangeComputationJob.java:44)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
</pre>

`checker.framework.quickfixes.FixerDescriptorApplier.apply().proposal = Change type of Lbh/Body$4373$Enumerate;.current)Lbh/Body; to @Initialized @Nullable Body`

**Comment by reprogrammer** [comment]
A workaround is to change jolden-bh not to declare innerclasses inside methods. After all, declaring inner classes inside methods is a rare practice. I [changed jodlen-bh](https://github.com/reprogrammer/tqi-study/commit/bf7fcd623d0a5622a2965bc4b0512207f81eac9f) and ensured that the workaround works.
